apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: etherpad
    namespace: argocd
spec:
    project: default
    sources:
      - path: .
        chart: etherpad
        repoURL: https://github.com/ether/ether-charts
        targetRevision: main
        helm:
          valueFiles:
            - values.yaml
            - <your-ref>/etherpad/values.yaml
          releaseName: etherpad
      - repoURL: <your-private-repo-url>
        targetRevision: <your-target-revision>
        ref: <your-ref>
    destination:
      server: "https://kubernetes.default.svc"
      namespace: etherpad
    syncPolicy:
      automated:
        prune: true
        selfHeal: false
      syncOptions:
        - CreateNamespace=true
